server:
  port: ${PORT:8761} # Indicate the default PORT where this service will be started 
eureka:
  client:
    registerWithEureka: false   #telling the server not to register himself in the service registry
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0    #wait time for subsequent sync
spring:
  oauth:
    user: demo
    password: $2a$04$I9Q2sDc4QGGg5WNTLmsz0.fvGv3OjoZyj81PrSFyGOqMphqfS2qKu
    client-id: demo-client
    client-secret: $2a$04$I9Q2sDc4QGGg5WNTLmsz0.fvGv3OjoZyj81PrSFyGOqMphqfS2qKu
zuul:
  prefix: /api
  routes:
    middleware:
      path: /service1/**
      url: http://localhost:8080/
